### ISSUE TITLE
Infografia -de-las librerias-EdwinOrtiz

### ISSUE THREAD

**Issue by EdwinOrtiz1412** [SistemasTecTlaxiaco/infografia-de-las-librerias-EdwinOrtiz1412#2]
[Infografia_4US.pdf](https://github.com/SistemasTecTlaxiaco/infografia-de-las-librerias-EdwinOrtiz1412/files/8219885/Infografia_4US.pdf)

**Comment by Sandra631** [comment]
20%

**Comment by josealfredo79** [comment]
Bien hecho y revisado
